# url是GIT服务器的仓库地址， searchPaths配置文件所在的文件夹在仓库中的路径,在server端不需要指定具体配置文件名
spring:
  application:
      name:  config-server
  rabbitmq:
      host: localhost
      port: 5672
      username: yuanshuaif
      password: Aa123456
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuanshuaif/SpringCloudConfig.git
          searchPaths: SpringCloudConfig

server:
  port : 8081
eureka:
    client:
        serviceUrl:
            defaultZone: http://yuanshuai:dk@localhost:8082/eureka/



